config/routes.rb
Rails.application.routes.draw do
  devise_for :publishers
  devise_for :editors
  devise_for :writers

  namespace :publishers do
    get 'tasks', to: 'tasks#index'
    post 'tasks/create', to: 'tasks#create'
    get 'tasks/new'
    get 'tasks/show', to: 'tasks#show'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/edit', to: 'tasks#edit'
    post 'tasks/delete', to: 'tasks#delete'
    post 'tasks/publish', to: 'tasks#publish'
    post 'tasks/unpublish', to: 'tasks#unpublish'

    get 'websites', to: 'websites#index'
  end

  namespace :writers do
    get 'articles', to: 'articles#index'
    get 'articles/new', to: 'articles#new'
    post 'articles/create', to: 'articles#create'
    get 'articles/show', to: 'articles#show'
    patch 'articles/update', to: 'articles#update'
    get 'articles/edit'
    post 'articles/update'
    post 'articles/delete', to: 'articles#delete'
    post 'articles/upload_picture', to: 'articles#upload_picture'

    get 'assigned_tasks/show', to: 'assigned_tasks#show'
  end

  namespace :editors do
    get 'tasks', to: 'tasks#index'
    get 'tasks/show', to: 'tasks#show'
    post 'tasks/assign', to: 'tasks#assign'
    post 'tasks/unassign', :controller => 'tasks', :action => 'unassign'
    get 'tasks/new', to: 'tasks#new'
    post 'tasks/create', to: 'tasks#create'
    post 'tasks/delete', :controller => 'tasks', :action => 'delete'
    get 'tasks/edit', to: 'tasks#edit'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/article', to: 'tasks#article'

    get 'assigned_tasks', to: 'assigned_tasks#index'
    post 'assigned_tasks/unassign', :controller => 'assigned_tasks', :action => 'unassign'
  end


end

app/models/article.rb
class Article < ActiveRecord::Base
	extend Enumerize
  default_scope {where(:deleted_at => nil)}

	enum status: {writing:0, finished_writing:1, keeping:2, editing:3, finished_editing:4, finish:5}

  belongs_to :writer
  belongs_to :assigned_task
  has_many :pictures

  validates :title, :presence => true
  validates :content, :presence => true

  def assigned_task_info ()
    self.assigned_task.task
  end

  def task_title ()
    self.assigned_task.task.title
  end
  
  def status_in_japanese ()
    if self.status == 'writing'
      '執筆中'
    elsif self.status == 'finished_writing'
      '原稿完成'
    elsif self.status == 'keeping'
      '編集預かり'
    elsif self.status == 'editing'
      '差し戻し'
    elsif self.status == 'finished_editing'
      '編集完了'
    elsif self.status == 'finish'
      '完成'
    else
      'Unknown Status'
    end
  end
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :articles
	has_many :assigned_tasks

	validates :name, presence: true

	def create_article (params)
		@params = params
		article = Article.new(article_params)
    unless article.assigned_task_id.nil?
      article.title = article.task_title
    end
    p article
    article.writer_id = self.id
    article.status = 'writing'
		article.save
		tokens = params[:tokens]
		unless tokens.nil?
			tokens.split(",").each do |token|
				lst = token.split(":")
				token1 = lst[0]
				token2 = lst[1]
				picture = Picture.where(:token1 => token1, :token2 => token2).first
				unless picture.nil?
					picture.article_id = article.id
					picture.save
				end
			end
		end
	end

	def update_article (params)
		@params = params
		article = Article.where(:id => params[:id]).first
		article.update_attributes(article_params)
		article.save
		tokens = params[:tokens]
		unless tokens.nil?
			tokens.split(",").each do |token|
				lst = token.split(":")
				token1 = lst[0]
				token2 = lst[1]
				picture = Picture.where(:token1 => token1, :token2 => token2).first
				unless picture.nil?
					picture.article_id = article.id
					picture.save
				end
			end
		end
	end

	def delete_article (params)
		article = Article.where(:id => params[:id]).first
		article.deleted_at = Time.now
		article.save
	end

	private
	def article_params ()
		@params.require(:article).permit(:content, :writer_id, :assigned_task_id, :created_at, :deleted_at, :updated_at, :title)
	end

  def finished_writing (params)
    article = Article.where(:id => params[:id]).first
    if article.writing?
      article.status = 'finished_writing'
    end
  end

  def writing (params)
    article = Article.where(:id => params[:id]).first
    article.status = 'writing'
  end

  def finished_editing (params)
    article = Article.where(:id => params[:id]).first
    article.status = 'finished_editing'
  end
end

app/controllers/writers/application_controller.rb
class Writers::ApplicationController < ApplicationController
  before_action :authenticate_writer!
  layout 'writers'
end

app/controllers/writers/articles_controller.rb
class Writers::ArticlesController < Writers::ApplicationController
  def index
		@articles = current_writer.articles
    @tasks = Task.assigned_all
  end

  def new
    unless params[:assigned_task_id].nil?
      @article = Article.new(:assigned_task_id => params[:assigned_task_id])
    else
      @article = Article.new
    end
    p @article
  end

  def create
		if current_writer.create_article(params)
			redirect_to writers_articles_path
		else
			redirect_to (:back)
		end
  end

	def show
		@article = Article.where(:id => params[:id]).first
    unless @article.assigned_task_id.nil?
      @task = @article.assigned_task_info
    end
	end

	def edit
		@article = Article.where(:id => params[:id]).first
	end


	def update
		if current_writer.update_article(params)
			redirect_to writers_articles_show_path(:id => params[:id])
		else
			 redirect_to (:back)
		end
	end

	def delete
		current_writer.delete_article(params)
		redirect_to writers_articles_path
	end

	def upload_picture
		picture = Picture.new
		picture.image = File.open(params["image"].tempfile)
		picture.image_file_name = params[:"image"].original_filename
		picture.token1 = params[:token1].to_i
		picture.token2 = params[:token2].to_i
		if picture.save
			render :file, picture.image
		else
			render :file, picture.image 
		end
	end

	def show_image
		picture = Picture.where(:token1 => params[:token1].to_i, :token2 => params[:token2].to_i).first
		if picture.nil?
			render :file, "#{Rails.root}/public/images/sample/sample.png"
		else
			render :file, picture.image
		end
	end
end

app/controllers/writers/assigned_tasks_controller.rb
class Writers::AssignedTasksController < Writers::ApplicationController

  def index
		@tasks = Task.assigned_all
  end

	def show
		@task = Task.where(:id => params[:id]).first
	end
end

app/helpers/writers/articles_helper.rb
module Writers::ArticlesHelper
end

app/helpers/writers/assigned_tasks_helper.rb
module Writers::AssignedTasksHelper
end

app/views/writers/articles/edit.html.haml
:scss
  .edit-article {
    .output-area {
      border-style: inset;
      border-width: 1px;
      height: 60rem;
      overflow: hidden;
    }
    .input-area {
      height: 60rem;
      width: 100%;
    }
  }
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab3 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      width: 100%;
    }
  .active#tab2_content {
      display: block;
      width: 100%;
    }
  .separate#tab1_content {
      display: block;
      width: 50%;
    }
  .separate#tab2_content {
      display: block;
      width: 50%;
    }
  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }
  #tab3 {
    color: green;
    opacity: 0.5;
  }
  input[type="submit"] {
    border-style: none;
    background-color: rgba(10,10,10,0.0); 
    color: #428bca;
    height: 42px;
    width: 75px;
  }


.container.edit-article
  .row
    = form_for @article, :url=> writers_articles_update_path(:id => @article[:id]) do |a|
      %ul.nav.nav-tabs
        %li.btn.btn-default#save= a.submit 'update'
        %li.btn.btn-default= link_to 'cancel', writers_articles_path
      .col-md-10
        - if @article.assigned_task_id.present?
          %h2= @article.task_title
          = a.hidden_field:assigned_task_id, :val=>@article.assigned_task_id
        - else
          = label :article, :title, :id => "title"
          = a.text_field:title, :autofocus => true, :s => '1'
        %ul.nav.nav-tabs
          %li.btn.btn-default.active#tab3{:tupe => "button"} Separate
          %li.btn.btn-default#tab1{:type => "button"} Article
          %li.btn.btn-default#tab2{:type => "button"} Preview
        .col-md-6#tab1_content.separate
          = a.text_area:content,:autofocus => :true, :cols=>'70', :class=>'input-area'
        .col-md-6.output-area#tab2_content.separate
          %p Result Area
        %input#tokens(style="display:none;" name="tokens")
      .col-md-2
        .uploader
:coffee
  change_tab = (name) ->
    $("#tab1_content, #tab2_content").removeClass("active")
    $("#tab1_content, #tab2_content").removeClass("separate")
    $("#tab1, #tab2, #tab3").removeClass("active")
    $(name).addClass("active")

  $ ->
    $("#tab1").click ->
      change_tab ("#tab1_content")
      $("#tab1").addClass("active")
    $("#tab2").click ->
      change_tab("#tab2_content")
      $("#tab2").addClass("active")
    $("#tab3").click ->
      $("#tab1, #tab2").removeClass("active")
      $(this).addClass("active")
      $("#tab1_content, #tab2_content").addClass("separate")

app/views/writers/articles/index.html.haml
:scss
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }
  .active#tab2_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }

  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }
 
.container.edit-article
  .row
    .col-md-10
      %ul.nav.nav-tabs
        %li
          %a.active#tab1.btn Articles
        %li
          %a#tab2.btn Tasks
      #tab1_content.active
        %li.btn.btn-default.btn-lg= link_to 'create article', writers_articles_new_path
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Title
              %th Due
              %th Status
              %th 詳細
              %th 削除
          %tbody
            -@articles.each do |article|
              %tr
                %td= article.title
                - if article.assigned_task.nil?
                  %td No Task
                - else 
                  %td= article.assigned_task.task.end_date.strftime("%m月%d日 %H:%M")
                %td= article.status_in_japanese
                %td= link_to 'show', writers_articles_show_path(:id => article.id)
                %td= link_to 'delete', writers_articles_delete_path(:id => article[:id]), :method => :post
      #tab2_content
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Title
              %th Due
              %th 本数
              %th 報酬
              %th 原稿数
              %th 詳細
          %tbody
            -@tasks.each do |task|
              %tr
                %td= task.title
                %td= task.end_date.strftime("%m月%d日 %H:%M")
                %td= task.number
                %td= task.reward
                %td= task.assigned_task.articles.count
                %td= link_to 'show', :controller => 'assigned_tasks', :action => 'show', :id => task[:id]
:coffee
  $("#tab1").click ->
    $("#tab1_content").addClass("active")
    $("#tab1").addClass("active")
    $("#tab2_content").removeClass("active")
    $("#tab2").removeClass("active")
  $("#tab2").click ->
    $("#tab2_content").addClass("active")
    $("#tab2").addClass("active")
    $("#tab1_content").removeClass("active")
    $("#tab1").removeClass("active")

app/views/writers/articles/new.html.haml
:scss
  .edit-article {
    .output-area {
      border-style: inset;
      border-width: 1px;
      height: 60rem;
      overflow: hidden;
    }
    .input-area {
      height: 60rem;
      width: 100%;
    }
    #title {
      margin-top: 20px;
      margin-bottom: 20px;
      font-size: 30px;
    }
    #article_title {
      margin-top: 20px;
      margin-bottom: 20px;
      margin-left: 20px;
      width: 500px;
      height: 40px;
      font-size: 30px;
    }
  }
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab3 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      width: 100%;
      padding: 0;
      overflow: hidden;
    }
  .active#tab2_content {
      display: block;
      width: 100%;
      overflow: hidden;
    }
  .separate#tab1_content {
      display: block;
      width: 50%;
      padding: 0;
      overflow: hidden;
    }
  .separate#tab2_content {
      display: block;
      width: 50%;
      padding: 0;
      overflow: hidden;
    }
  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }
  #tab3 {
    color: green;
    opacity: 0.5;
  }
  input[type="submit"] {
    border-style: none;
    background-color: rgba(10,10,10,0.0); 
    color: #428bca;
    height: 42px;
    width: 75px;
  }


.container.edit-article
  .row
    = form_for @article, :url=> writers_articles_create_path do |a|
      %ul.nav.nav-tabs
        %li.btn.btn-default#save= a.submit 'create'
        %li.btn.btn-default.link= link_to 'cancel', writers_articles_path
      .col-md-10
        - if @article.assigned_task_id.present?
          %h2= @article.task_title
          = a.hidden_field:assigned_task_id, :val=>@article.assigned_task_id
        - else
          = label :article, :title, :id => "title"
          = a.text_field:title, :autofocus => true, :s => '1'
        %ul.nav.nav-tabs
          %li.btn.btn-default.active#tab3{:tupe => "button"} Separate
          %li.btn.btn-default#tab1{:type => "button"} Article
          %li.btn.btn-default#tab2{:type => "button"} Preview
        .col-md-6#tab1_content.separate
          = a.text_area:content,:autofocus => :true, :cols=>'70', :class=>'input-area'
        .col-md-6.output-area#tab2_content.separate
          %p Result Area
        %input#tokens(style="display:none;" name="tokens")
      .col-md-2
        .uploader

:coffee
  change_tab = (name) ->
    $("#tab1_content, #tab2_content").removeClass("active")
    $("#tab1_content, #tab2_content").removeClass("separate")
    $("#tab1, #tab2, #tab3").removeClass("active")
    $(name).addClass("active")

  $ ->
    $("#tab1").click ->
      change_tab ("#tab1_content")
      $("#tab1").addClass("active")
    $("#tab2").click ->
      change_tab("#tab2_content")
      $("#tab2").addClass("active")
    $("#tab3").click ->
      $("#tab1, #tab2").removeClass("active")
      $(this).addClass("active")
      $("#tab1_content, #tab2_content").addClass("separate")

app/views/writers/articles/show.html.haml
:scss
  #article_content_space {
    display: block;
    border-style: inset;
    border-width: 1px;
    overflow: hidden;
    }
  #task_description_space {
    display: block;
    border-style: inset;
    border-width: 1px;
    overflow: hidden;
    }
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }
  .active#tab2_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }

  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }
  
%div.container.show-article
  %div.row
    %div.col-md-10
      %ul.nav.nav-tabs
        %a#tab1.btn.active Article
        - unless @article.assigned_task_id.nil?
          %a#tab2.btn Task
      %ul.nav.nav-tabs
        %li.btn= link_to 'edit', writers_articles_edit_path(:id => @article.id)
        %li.btn= link_to 'back', writers_articles_path
        %li.btn= link_to 'delete', writers_articles_delete_path(:id => @article.id), :method => :post
      #tab1_content.active
        %h2= @article.title
        %textarea#article_content(style="display: none;")= @article.content
        #article_content_space
      - unless @article.assigned_task_id.nil?
        #tab2_content
          %h1= @task.title
          %label Due
          = @task.end_date.strftime("%m月%d日 %H:%M")
          %br
          %label 報酬
          = @task.reward
          %br
          %label 本数
          = @task.number
          %textarea#task_description(style="display: none;")= @task.description
          #task_description_space

:coffee
  $("#article_content_space").html(marked($("#article_content").html()))
  $("#task_description_space").html(marked($("#task_description").html()))
  $("#tab1").click ->
    $("#tab1_content").addClass("active")
    $("#tab1").addClass("active")
    $("#tab2_content").removeClass("active")
    $("#tab2").removeClass("active")
  $("#tab2").click ->
    $("#tab2_content").addClass("active")
    $("#tab2").addClass("active")
    $("#tab1_content").removeClass("active")
    $("#tab1").removeClass("active")