config/routes.rb
Rails.application.routes.draw do
  devise_for :publishers
  devise_for :editors
  devise_for :writers

  namespace :publishers do
    get 'tasks', to: 'tasks#index'
    post 'tasks/create', to: 'tasks#create'
    get 'tasks/new'
    get 'tasks/show', to: 'tasks#show'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/edit', to: 'tasks#edit'
    post 'tasks/delete', to: 'tasks#delete'
    post 'tasks/publish', to: 'tasks#publish'
    post 'tasks/unpublish', to: 'tasks#unpublish'

    get 'websites', to: 'websites#index'
  end

  namespace :writers do
    get 'articles', to: 'articles#index'
    get 'articles/new', to: 'articles#new'
    post 'articles/create', to: 'articles#create'
    get 'articles/show', to: 'articles#show'
    patch 'articles/update', to: 'articles#update'
    get 'articles/edit'
    post 'articles/update'
    post 'articles/delete', to: 'articles#delete'
    post 'articles/upload_picture', to: 'articles#upload_picture'

    get 'assigned_tasks/show', to: 'assigned_tasks#show'
  end

  namespace :editors do
    get 'tasks', to: 'tasks#index'
    get 'tasks/show', to: 'tasks#show'
    post 'tasks/assign', to: 'tasks#assign'
    post 'tasks/unassign', :controller => 'tasks', :action => 'unassign'
    get 'tasks/new', to: 'tasks#new'
    post 'tasks/create', to: 'tasks#create'
    post 'tasks/delete', :controller => 'tasks', :action => 'delete'
    get 'tasks/edit', to: 'tasks#edit'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/article', to: 'tasks#article'

    get 'assigned_tasks', to: 'assigned_tasks#index'
    post 'assigned_tasks/unassign', :controller => 'assigned_tasks', :action => 'unassign'
  end


end

app/models/editor.rb
class Editor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  include TaskCreatable
  include TaskDeletable

  has_many :assigned_tasks
  has_many :tasks, :as => :task_creatable

  validates :name, presence: true

  def assigned_tasks_list
    result = []
    self.assigned_tasks.each do |atask|
      result << atask.task
    end
    result
  end

  def keeping (params)
    article = Article.where(:id => parms[:id]).first
    if article.status == 'finished_writing'
      article.status = 'keeping'
    end
  end

  def editing (params)
    article = Article.where(:id => parms[:id]).first
    if article.status == 'keeping' || article.status == 'finished_editing'
      article.status == 'editing'
    end
  end

  def finish (params)
    article = Article.where(:id => params[:id]).first
    if article.status == 'editing'
      article.status == 'finish'
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
	extend Enumerize
	default_scope {where(:deleted_at => nil)}

	enum status: {unpublished:0, published:1, closed:2}

	belongs_to :task_creatable, :polymorphic => true
	belongs_to :category
	has_one :assigned_task
  has_many :websites

	validates :title, presence: true
	validates :description, presence: true
	validates :reward, presence: true
	validates :reward, numericality: :only_integer
	validates :status, presence: true

	def unpublished? ()
		not self.published?
	end

	def publish ()
		unless self.status == :published
			self.status = :published
			self.save
		end
	end

	def unpublish ()
		unless self.status == :unpublished
			self.status = :unpublished
			self.save
		end
	end

	def close ()
		unless self.status == :closed
			self.status = :closed
			self.save
		end
	end

	def unclose ()
		if self.status == :closed
			self.status = :unpublished
			self.save
		end
	end
	def assign (params)
		unless Task.where(:id => self.id).first.assigned?
			task = AssignedTask.new()
			task.task_id = self.id
			task.editor_id = params[:editor_id]
			task.save
		end
	end

	def unassign ()
		self.assigned_task.destroy
	end
			
	def assigned? ()
		self.assigned_task.present?
	end

	def who_assigned ()
		self.assigned_task.editor
	end

	def self.assigned_all ()
		result = []
		Task.all.each do |task|
			if task.assigned?
				result << task
			end
		end
		result
	end

	def self.unassigned_all ()
		result = []
		Task.all.each do |task|
			unless task.assigned?
				result << task
			end
		end
		result
	end
end

app/controllers/editors/application_controller.rb
class Editors::ApplicationController < ApplicationController
  before_action :authenticate_editor!
  layout 'editors'
end

app/controllers/editors/assigned_tasks_controller.rb
class Editors::AssignedTasksController < Editors::ApplicationController
	def unassign
		task = Task.where(:id => params[:id]).first
		task.unassign
		redirect_to editors_assigned_tasks_path
	end
end

app/controllers/editors/tasks_controller.rb
class Editors::TasksController < Editors::ApplicationController
  def index
    @tasks = Task.all
    @mytasks = current_editor.tasks
    @myassigned_tasks = current_editor.assigned_tasks_list
  end

  def show
    @task = Task.where(:id=>params[:id]).first
    @articles = @task.assigned_task.articles
  end

  def assign
    task = Task.where(:id=>params[:id]).first
    task.assign(params)
    redirect_to (:back)
  end

  def unassign
    task = Task.where(:id => params[:id]).first
    task.unassign
    redirect_to (:back)
  end

  def create 
    if current_editor.create_task(params)
      redirect_to editors_tasks_path
    else
      redirect_to (:back)
    end
  end

  def edit
    @task = Task.where(:id => params[:id]).first
  end

  def update
    editor = Editor.new
    if editor.update_task(params)
      redirect_to editors_tasks_show_path(:id => params[:id])
    else
      redirect_to (:back)
    end
  end

  def new
    @task = Task.new
  end

  def delete
    editor = Editor.new
    editor.delete_task(params)
    redirect_to :controller => 'tasks', :action => 'index'
  end

  def article
    @article = Article.where(:id => params[:id]).first
    unless @article.assigned_task_id.nil?
      @task = @article.assigned_task_info
    end
  end
end

app/controllers/publishers/tasks_controller.rb
class Publishers::TasksController < Publishers::ApplicationController

	def index
		@tasks=Task.all
    @mytasks = current_publisher.tasks
	end

	def create
		publisher = Publisher.new
		if publisher.create_task(params)
			redirect_to '/publishers/tasks'
		else
			redirect_to '/publishers/tasks/new'
		end
	end

	def show
		@task = Task.where(:id => params[:id]).first
	end

	def new
		@task = Task.new
	end

	def update
		publisher = Publisher.new
		if publisher.update_task(params)
			redirect_to publishers_tasks_show_path(:id => params[:id])
		else
			redirect_to (:back)
		end
	end

	def edit
		@task = Task.where(:id => params[:id]).first
	end

	def delete
		publisher = Publisher.new
		publisher.delete_task(params)
		redirect_to publishers_tasks_path
	end

	def publish
		task = Task.where(:id => params[:id]).first
		if task.publish
			redirect_to (:back)
		end
	end

	def unpublish
		task = Task.where(:id => params[:id]).first
		if task.unpublish
			redirect_to (:back)
		end
	end
	private

	def task_params
		params.require(:task).permit(:title, :description, :start_date, :end_date, :reward, :number, :agreement)
	end

end

app/helpers/editors/assigned_tasks_helper.rb
module Editors::AssignedTasksHelper
end

app/helpers/editors/tasks_helper.rb
module Editors::TasksHelper
end

app/helpers/publishers/tasks_helper.rb
module Publishers::TasksHelper
end

app/views/editors/tasks/article.html.haml
:scss
  #article_content_space {
    display: block;
    border-style: inset;
    border-width: 1px;
    overflow: hidden;
    }
  #task_description_space {
    display: block;
    border-style: inset;
    border-width: 1px;
    overflow: hidden;
    }
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }
  .active#tab2_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }

  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }
  
%div.container.show-article
  %div.row
    %div.col-md-10
      %ul.nav.nav-tabs
        %a#tab1.btn.active Article
        - unless @article.assigned_task_id.nil?
          %a#tab2.btn Task
      %ul.nav.nav-tabs
        %li.btn= link_to 'back', editors_tasks_show_path(:id => @task.id)
      #tab1_content.active
        %h2= @article.title
        %textarea#article_content(style="display: none;")= @article.content
        #article_content_space
      - unless @article.assigned_task_id.nil?
        #tab2_content
          %h1= @task.title
          %label Due
          = @task.end_date.strftime("%m月%d日 %H:%M")
          %br
          %label 報酬
          = @task.reward
          %br
          %label 本数
          = @task.number
          %textarea#task_description(style="display: none;")= @task.description
          #task_description_space

:coffee
  $("#article_content_space").html(marked($("#article_content").html()))
  $("#task_description_space").html(marked($("#task_description").html()))
  $("#tab1").click ->
    $("#tab1_content").addClass("active")
    $("#tab1").addClass("active")
    $("#tab2_content").removeClass("active")
    $("#tab2").removeClass("active")
  $("#tab2").click ->
    $("#tab2_content").addClass("active")
    $("#tab2").addClass("active")
    $("#tab1_content").removeClass("active")
    $("#tab1").removeClass("active")

app/views/editors/tasks/edit.html.haml
:scss
  .edit-task {
    padding-top: 5rem;
    padding-bottom: 5rem;
    #task_title {
      width: 500px;
      height: 6rem;
    }
    .output-area {
      border-style: solid;
      height: 21rem;
      width: 440px;
    }
    .input-area {
      height: 20rem;
      width: 440px;
    }
    .btns {
      padding-top: 2rem;
    }
  }

.container
  .row
    = form_for @task, :url=>editors_tasks_update_path(:id=>@task[:id]) do |t|
      .col-md-8
        %table.table.table-striped.table-bordered
          %tr
            %td Title
            %td= t.text_field:title
            %br
          %tr
            %td Description
            %td= t.text_area:description
            %br
          %tr
            %td StartDate
            %td= t.date_select:start_date
            %br
          %tr
            %td EndDate
            %td= t.date_select:end_date
            %br
          %tr
            %td Reward
            %td= t.number_field:reward
            %br
          %tr
            %td Number
            %td= t.number_field:number
            %br
      %div.col-md-2
        %ul.nav.nav-stacked
          %li= t.submit 'update', :id => @task[:id]
          %li= link_to 'cancel', '/editors/tasks'

app/views/editors/tasks/index.html.haml
:scss
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab3 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }
  .active#tab2_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }
  .active#tab3_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }

  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab3_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }
  #tab3 {
    color: green;
    opacity: 0.5;
  }
  .table {
    width: 100%;
  }
 
%div.container.task-index
  %div.row
    %div.col-md-10
      %ul.nav.nav-tabs
        %li
          %a.active#tab1.btn Tasks
        %li
          %a#tab2.btn Assigned Tasks
        %li
          %a#tab3.btn Created Tasks
      = link_to 'Create Task', editors_tasks_new_path,{:class => "btn btn-default btn-lg"}
      #tab1_content.active
        %table.table.table-striped.table-bodered
          %thead
            %tr
              %th Title
              %th Due
              %th 本数
              %th 報酬
              %th Assigned?
              %th 原稿数
              %th 詳細
              %th Assign
          %tbody
            -@tasks.each do |task|
              %tr
                %td= task.title
                %td= task.end_date.strftime("%m月%d日 %H:%M")
                %td= task.number
                %td= task.reward
                -if task.assigned?
                  %td Assigned
                -else
                  %td Not Yet
                -if task.assigned?
                  %td= task.assigned_task.articles.count
                - else 
                  %td 0
                %td= link_to 'show', editors_tasks_show_path(:id => task.id)
                %td= link_to 'assign', editors_tasks_assign_path(:id => task.id, :editor_id => current_editor.id), :method => :post
      #tab2_content
        %table.table.table-striped.table-bodered
          %thead
            %tr
              %th Title
              %th Due
              %th 本数
              %th 報酬
              %th 公開
              %th 原稿数
              %th 詳細
          %tbody
            -@myassigned_tasks.each do |task|
              %tr
                %td= task.title
                %td= task.end_date.strftime("%m月%d日 %H:%M")
                %td= task.number
                %td= task.reward
                - if task.published?
                  %td 公開済
                - else
                  %td 未公開
                %td= task.assigned_task.articles.count
                %td= link_to 'show', editors_tasks_show_path(:id => task.id)
      #tab3_content
        %table.table.table-striped.table-bodered
          %thead
            %tr
              %th Title
              %th Due
              %th 本数
              %th 報酬
              %th 詳細
          %tbody
            -@mytasks.each do |task|
              %tr
                %td= task.title
                %td= task.end_date.strftime("%m月%d日 %H:%M")
                %td= task.number
                %td= task.reward
                %td= link_to 'show', editors_tasks_show_path(:id => task[:id])
:coffee
  $("#tab1").click ->
      $("#tab1_content, #tab2_content, #tab3_content").removeClass("active")
      $("#tab1, #tab2, #tab3").removeClass("active")
      $("#tab1_content").addClass("active")
      $("#tab1").addClass("active")
    $("#tab2").click ->
      $("#tab1_content, #tab2_content, #tab3_content").removeClass("active")
      $("#tab1, #tab2, #tab3").removeClass("active")
      $("#tab2_content").addClass("active")
      $("#tab2").addClass("active")
    $("#tab3").click ->
      $("#tab1_content, #tab2_content, #tab3_content").removeClass("active")
      $("#tab1, #tab2, #tab3").removeClass("active")
      $("#tab3_content").addClass("active")
      $("#tab3").addClass("active")

app/views/editors/tasks/new.html.haml
:scss
  #title {
    margin-top: 20px;
    font-size: 25px;
  }
  #task_title {
    margin-top: 20px;
    width: 500px;
    height: 40px;
    font-size: 30px;
  }
  .output-area {
    border-style: solid;
    height: 400px;
  }
  .input-area {
    height: 400px;
    width: 100%;
  }
  .btns {
    padding-top: 2rem;
  }
  input[type="submit"] {
    border-style: none;
    background-color: rgba(10,10,10,0.0); 
    color: #428bca;
    height: 42px;
    width: 75px;
  }
.container.edit-task
  .row
    .col-md-10
      = form_for @task, :url => editors_tasks_create_path do |t|
        %ul.nav.nav-tabs
          %li.btn.btn-default#save= t.submit 'create'
          %li.btn.btn-default.link= link_to 'cancel', editors_tasks_path
        = label :task, :title, :id => "title"
        = t.text_field:title, :autofocus => true, :s => '1'
        %br
        .col-md-12
          .col-md-6
            = t.text_area:description, :cols=>'70', :class=>'input-area'
          .col-md-6.output-area
            %p Result Area
        = label :task, :start_date
        = t.datetime_select:start_date
        %br
        = label :task, :end_date
        = t.datetime_select:end_date
        %br
        = label :task, :reward
        = t.number_field:reward
        %br
        = label :task, :number
        = t.number_field:number

app/views/editors/tasks/show.html.haml
:scss
  #task_description_space {
    display: block;
    border-style: inset;
    border-width: 1px;
    overflow: hidden;
    }
  .active#tab1 {
      color: green;
      opacity: 0.8;
    }
  .active#tab2 {
      color: green;
      opacity: 0.8;
    }
  .active#tab1_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }
  .active#tab2_content {
      display: block;
      padding: 20px 20px 20px 20px;
    }

  #tab1_content {
    display: none;
  }
  #tab2_content {
    display: none;
  }
  #tab1 {
    color: green;
    opacity: 0.5;
  }
  #tab2 {
    color: green;
    opacity: 0.5;
  }

%div.container
  %div.row
    %div.col-md-10
      %ul.nav.nav-tabs
        %li
          %a.active#tab1.btn Task
        %li
          -unless @articles.empty?
            %a#tab2.btn Articles
      %ul.nav.nav-tabs
        %li= link_to 'back', '/editors/tasks'
        - if @task.task_creatable_type=='editor' && @task.task_creatable_id==current_editor.id
          %li= link_to 'edit', :controller => 'tasks', :action => 'edit', :id => @task[:id]
          %li= link_to 'delete', editors_tasks_delete_path(:id => @task[:id]), :method => :post
        - unless @task.assigned?
          %li= link_to 'assign', editors_tasks_assign_path(:id => @task[:id],:editor_id => current_editor.id), :method => :post
        - if @task.assigned_task.editor_id == current_editor.id
          %li= link_to 'unassign', editors_assigned_tasks_unassign_path(:id => @task[:id]), :method => :post
      #tab1_content.active
        %h2= @task.title
        %textarea#task_description(style="display: none;")= @task.description
        #task_description_space
      - unless @articles.empty?
        #tab2_content
          %table.table.table-striped.table-bordered
            %thead
              %th Name
              %th Status
              %th Update
              %th 詳細
            -@articles.each do |article|
              %tbody
                %td= article.writer.name
                %td= article.status_in_japanese
                %td= article.updated_at
                %td= link_to 'show', editors_tasks_article_path(:id => article.id)
:coffee
  $("#tab1").click ->
    $("#tab1_content").addClass("active")
    $("#tab1").addClass("active")
    $("#tab2_content").removeClass("active")
    $("#tab2").removeClass("active")
  $("#tab2").click ->
    $("#tab2_content").addClass("active")
    $("#tab2").addClass("active")
    $("#tab1_content").removeClass("active")
    $("#tab1").removeClass("active")
  $("#task_description_space").html(marked($("#task_description").html()))