config/routes.rb
Rails.application.routes.draw do
  devise_for :publishers
  devise_for :editors
  devise_for :writers

  namespace :publishers do
    get 'tasks', to: 'tasks#index'
    post 'tasks/create', to: 'tasks#create'
    get 'tasks/new'
    get 'tasks/show', to: 'tasks#show'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/edit', to: 'tasks#edit'
    post 'tasks/delete', to: 'tasks#delete'
    post 'tasks/publish', to: 'tasks#publish'
    post 'tasks/unpublish', to: 'tasks#unpublish'

    get 'websites', to: 'websites#index'
  end

  namespace :writers do
    get 'articles', to: 'articles#index'
    get 'articles/new', to: 'articles#new'
    post 'articles/create', to: 'articles#create'
    get 'articles/show', to: 'articles#show'
    patch 'articles/update', to: 'articles#update'
    get 'articles/edit'
    post 'articles/update'
    post 'articles/delete', to: 'articles#delete'
    post 'articles/upload_picture', to: 'articles#upload_picture'

    get 'assigned_tasks/show', to: 'assigned_tasks#show'
  end

  namespace :editors do
    get 'tasks', to: 'tasks#index'
    get 'tasks/show', to: 'tasks#show'
    post 'tasks/assign', to: 'tasks#assign'
    post 'tasks/unassign', :controller => 'tasks', :action => 'unassign'
    get 'tasks/new', to: 'tasks#new'
    post 'tasks/create', to: 'tasks#create'
    post 'tasks/delete', :controller => 'tasks', :action => 'delete'
    get 'tasks/edit', to: 'tasks#edit'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/article', to: 'tasks#article'

    get 'assigned_tasks', to: 'assigned_tasks#index'
    post 'assigned_tasks/unassign', :controller => 'assigned_tasks', :action => 'unassign'
  end


end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	include TaskCreatable
	include TaskDeletable

  has_many :websites
	has_many :tasks, :as => :task_creatable

	validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
	extend Enumerize
	default_scope {where(:deleted_at => nil)}

	enum status: {unpublished:0, published:1, closed:2}

	belongs_to :task_creatable, :polymorphic => true
	belongs_to :category
	has_one :assigned_task
  has_many :websites

	validates :title, presence: true
	validates :description, presence: true
	validates :reward, presence: true
	validates :reward, numericality: :only_integer
	validates :status, presence: true

	def unpublished? ()
		not self.published?
	end

	def publish ()
		unless self.status == :published
			self.status = :published
			self.save
		end
	end

	def unpublish ()
		unless self.status == :unpublished
			self.status = :unpublished
			self.save
		end
	end

	def close ()
		unless self.status == :closed
			self.status = :closed
			self.save
		end
	end

	def unclose ()
		if self.status == :closed
			self.status = :unpublished
			self.save
		end
	end
	def assign (params)
		unless Task.where(:id => self.id).first.assigned?
			task = AssignedTask.new()
			task.task_id = self.id
			task.editor_id = params[:editor_id]
			task.save
		end
	end

	def unassign ()
		self.assigned_task.destroy
	end
			
	def assigned? ()
		self.assigned_task.present?
	end

	def who_assigned ()
		self.assigned_task.editor
	end

	def self.assigned_all ()
		result = []
		Task.all.each do |task|
			if task.assigned?
				result << task
			end
		end
		result
	end

	def self.unassigned_all ()
		result = []
		Task.all.each do |task|
			unless task.assigned?
				result << task
			end
		end
		result
	end
end

app/controllers/editors/tasks_controller.rb
class Editors::TasksController < Editors::ApplicationController
  def index
    @tasks = Task.all
    @mytasks = current_editor.tasks
    @myassigned_tasks = current_editor.assigned_tasks_list
  end

  def show
    @task = Task.where(:id=>params[:id]).first
    @articles = @task.assigned_task.articles
  end

  def assign
    task = Task.where(:id=>params[:id]).first
    task.assign(params)
    redirect_to (:back)
  end

  def unassign
    task = Task.where(:id => params[:id]).first
    task.unassign
    redirect_to (:back)
  end

  def create 
    if current_editor.create_task(params)
      redirect_to editors_tasks_path
    else
      redirect_to (:back)
    end
  end

  def edit
    @task = Task.where(:id => params[:id]).first
  end

  def update
    editor = Editor.new
    if editor.update_task(params)
      redirect_to editors_tasks_show_path(:id => params[:id])
    else
      redirect_to (:back)
    end
  end

  def new
    @task = Task.new
  end

  def delete
    editor = Editor.new
    editor.delete_task(params)
    redirect_to :controller => 'tasks', :action => 'index'
  end

  def article
    @article = Article.where(:id => params[:id]).first
    unless @article.assigned_task_id.nil?
      @task = @article.assigned_task_info
    end
  end
end

app/controllers/publishers/application_controller.rb
class Publishers::ApplicationController < ApplicationController
  before_action :authenticate_publisher!
  layout 'publishers'
end

app/controllers/publishers/tasks_controller.rb
class Publishers::TasksController < Publishers::ApplicationController

	def index
		@tasks=Task.all
    @mytasks = current_publisher.tasks
	end

	def create
		publisher = Publisher.new
		if publisher.create_task(params)
			redirect_to '/publishers/tasks'
		else
			redirect_to '/publishers/tasks/new'
		end
	end

	def show
		@task = Task.where(:id => params[:id]).first
	end

	def new
		@task = Task.new
	end

	def update
		publisher = Publisher.new
		if publisher.update_task(params)
			redirect_to publishers_tasks_show_path(:id => params[:id])
		else
			redirect_to (:back)
		end
	end

	def edit
		@task = Task.where(:id => params[:id]).first
	end

	def delete
		publisher = Publisher.new
		publisher.delete_task(params)
		redirect_to publishers_tasks_path
	end

	def publish
		task = Task.where(:id => params[:id]).first
		if task.publish
			redirect_to (:back)
		end
	end

	def unpublish
		task = Task.where(:id => params[:id]).first
		if task.unpublish
			redirect_to (:back)
		end
	end
	private

	def task_params
		params.require(:task).permit(:title, :description, :start_date, :end_date, :reward, :number, :agreement)
	end

end

app/controllers/publishers/websites_controller.rb
class Publishers::WebsitesController < Publishers::ApplicationController
  def index
    @websites = current_publisher.websites
  end
end

app/helpers/editors/tasks_helper.rb
module Editors::TasksHelper
end

app/helpers/publishers/tasks_helper.rb
module Publishers::TasksHelper
end

app/helpers/publishers/websites_helper.rb
module Publishers::WebsitesHelper
end

app/views/publishers/tasks/deleted_tasks.html.haml
%div.content
%h1 Deleted Tasks
%table
  %thead
    %tr
      %th id
      %th title
      %th description
      %th start
      %th end
      %th number
      %th reward
  %tbody
    -@tasks.each do |task|
      %tr
        %td= task[:id]
        %td= task[:title]
        %td= task[:description]
        %td= task[:start_date]
        %td= task[:end_date]
        %td= task[:number]
        %td= task[:reward]
        %td= link_to 'show', :controller => 'tasks', :action => 'show', :id => task[:id]
        %td= link_to 'delete', :controller => 'tasks', :action => 'delete', :task=>task
= link_to "create new task", publishers_tasks_new_path
= link_to "Tasks", publishers_tasks_path

app/views/publishers/tasks/edit.html.haml
:scss
  .edit-task {
    padding-top: 5rem;
    padding-bottom: 5rem;
    #task_title {
      width: 500px;
      height: 6rem;
    }
    .output-area {
      border-style: solid;
      height: 21rem;
      width: 440px;
    }
    .input-area {
      height: 20rem;
      width: 440px;
    }
    .btns {
      padding-top: 2rem;
    }
  }

%div.container.edit-task
  %div.row
    = form_for @task, :url=>publishers_tasks_update_path(:id=>@task.id) do |t|
      %div.col-md-10
        %h2 Title
        %br
        = t.text_field:title
        %br
        %h2 Description
        %div.col-md-6
          = t.text_area:description, :cols=>'30', :rows=>'5',:class=>'input-area'
        %div.output-area.col-md-6
          %p Result Area
        %h3 StartDate
        = t.date_select:start_date
        %br
        %h3 EndDate
        = t.date_select:end_date
        %br
        %h3 Reward
        %td= t.number_field:reward
        %h3 Number
        = t.number_field:number
        %br
      %div.col-md-2
        %ul.btns
          %li.btn.btn-lg= t.submit 'update'
          %li.btn.btn-lg= link_to 'cancel', '/publishers/tasks'

app/views/publishers/tasks/index.html.haml
:scss
  .task-index {
    padding-top: 5rem;
    padding-bottom: 5rem;
  }

%div.container.task-index
  %div.row
    %div.col-md-8
      = link_to 'Create Task', publishers_tasks_new_path,{:class => "btn btn-default btn-lg"}
      %table.table
        %thead
          %tr
            %th id
            %th title
            %th start
            %th end
            %th number
            %th reward
            %th published?
            %th
            %th
            %th
        %tbody
          -@tasks.each do |task|
            %tr
              %td= task.id
              %td= task.title
              %td= task.start_date
              %td= task.end_date
              %td= task.number
              %td= task.reward
              - if task.published?
                %td published!
              - else
                %td Not published yet!
              %td= link_to 'show', :controller => 'tasks', :action => 'show', :id => task[:id]
              - if task.published?
                %td= link_to 'unpublish', publishers_tasks_unpublish_path(:id => task[:id]), :method => :post
              - else
                %td= link_to 'publish', publishers_tasks_publish_path(:id => task[:id]), :method => :post
              %td= link_to 'delete', publishers_tasks_delete_path(:id => task[:id]), :method => :post
    %div.col-md-4

app/views/publishers/tasks/new.html.haml
:scss
  #title {
    margin-top: 20px;
    font-size: 25px;
  }
  #task_title {
    margin-top: 20px;
    width: 500px;
    height: 40px;
    font-size: 30px;
  }
  .output-area {
    border-style: solid;
    height: 400px;
  }
  .input-area {
    height: 400px;
    width: 100%;
  }
  .btns {
    padding-top: 2rem;
  }
  input[type="submit"] {
    border-style: none;
    background-color: rgba(10,10,10,0.0); 
    color: #428bca;
    height: 42px;
    width: 75px;
  }
.container.edit-task
  .row
    .col-md-10
      = form_for @task, :url => publishers_tasks_create_path do |t|
        %ul.nav.nav-tabs
          %li.btn.btn-default#save= t.submit 'create'
          %li.btn.btn-default.link= link_to 'cancel', publishers_tasks_path
        = label :task, :title, :id => "title"
        = t.text_field:title, :autofocus => true, :s => '1'
        %br
        .col-md-12
          .col-md-6
            = t.text_area:description, :cols=>'70', :class=>'input-area'
          .col-md-6.output-area
            %p Result Area
        = label :task, :start_date
        = t.datetime_select:start_date
        %br
        = label :task, :end_date
        = t.datetime_select:end_date
        %br
        = label :task, :reward
        = t.number_field:reward
        %br
        = label :task, :number
        = t.number_field:number

app/views/publishers/tasks/show.html.haml
%div.containew
  %div.row
    %div.col-md-10
      %h1= @task[:title]
      %table.table.table-striped.table-bordered
        %body
          - @task.attribute_names.each do |key|
            %tr
              %td= key
              - if key != "status"
                %td= @task[key] 
              - else 
                %td= @task.status
      - if @task.assigned?
        %p= @task.who_assigned
    %div.col-md-2
      %ul.nav.nav-stacked
        %li= link_to 'back', '/publishers/tasks'
        %li= link_to 'edit', publishers_tasks_edit_path(:id => @task[:id])
        - if @task.published?
          %li= link_to 'unpublish', publishers_tasks_unpublish_path(:id => @task[:id]), :method => :post
        - else
          %li= link_to 'publish', publishers_tasks_publish_path(:id => @task[:id]), :method => :post
        %li= link_to 'delete', publishers_tasks_delete_path(:id => @task[:id]), :method => :post