config/routes.rb
Rails.application.routes.draw do
  devise_for :publishers
  devise_for :editors
  devise_for :writers

  namespace :publishers do
    get 'tasks', to: 'tasks#index'
    post 'tasks/create', to: 'tasks#create'
    get 'tasks/new'
    get 'tasks/show', to: 'tasks#show'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/edit', to: 'tasks#edit'
    post 'tasks/delete', to: 'tasks#delete'
    post 'tasks/publish', to: 'tasks#publish'
    post 'tasks/unpublish', to: 'tasks#unpublish'

    get 'websites', to: 'websites#index'
  end

  namespace :writers do
    get 'articles', to: 'articles#index'
    get 'articles/new', to: 'articles#new'
    post 'articles/create', to: 'articles#create'
    get 'articles/show', to: 'articles#show'
    patch 'articles/update', to: 'articles#update'
    get 'articles/edit'
    post 'articles/update'
    post 'articles/delete', to: 'articles#delete'
    post 'articles/upload_picture', to: 'articles#upload_picture'

    get 'assigned_tasks/show', to: 'assigned_tasks#show'
  end

  namespace :editors do
    get 'tasks', to: 'tasks#index'
    get 'tasks/show', to: 'tasks#show'
    post 'tasks/assign', to: 'tasks#assign'
    post 'tasks/unassign', :controller => 'tasks', :action => 'unassign'
    get 'tasks/new', to: 'tasks#new'
    post 'tasks/create', to: 'tasks#create'
    post 'tasks/delete', :controller => 'tasks', :action => 'delete'
    get 'tasks/edit', to: 'tasks#edit'
    patch 'tasks/update', to: 'tasks#update'
    get 'tasks/article', to: 'tasks#article'

    get 'assigned_tasks', to: 'assigned_tasks#index'
    post 'assigned_tasks/unassign', :controller => 'assigned_tasks', :action => 'unassign'
  end


end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Someworks
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/editors.html.haml
!!!
%html
  %head
    %title Someworks
    = stylesheet_link_tag    'application', media: 'all', :debug => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-10
          = image_tag "img_sitelogo.png", style: "width:160px; height:35px;margin-left: 20px; margin: 15px;"
        .col-md-2
          = link_to "Logout", destroy_editor_session_path, :method => :post
    = yield

app/views/layouts/publishers.html.haml
!!!
%html
  %head
    %title Someworks
    = stylesheet_link_tag    'application', media: 'all', :debug => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-10
          = image_tag "img_sitelogo.png", style: "width:160px; height:35px;margin-left: 20px; margin: 15px;"
        .col-md-2
          = link_to "Logout", destroy_publisher_session_path, :method => :post
    = yield

app/views/layouts/writers.html.haml
!!!
%html
  %head
    %title Someworks
    = stylesheet_link_tag    'application', media: 'all', :debug => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-10
          = image_tag "img_sitelogo.png", style: "width:160px; height:35px;margin-left: 20px; margin: 15px;"
        .col-md-2
          = link_to "Logout", destroy_writer_session_path, :method => :delete
    = yield